const TAGS=new Set(['a','article','div','dl','dt','dd','figure','figcaption','h1','h2','h3','img','li','main','p','pre','section','span','strong','table','tbody','td','th','tr','ul']);
const ATTRIBUTES=new Set(['alt','class','href','loading','src']);
function safeUrl(value) { return typeof value==='string'&&(/^(?:https:|mailto:|\/)/.test(value)||value.startsWith('./')); }
function append(parent,value,document) { if(!TAGS.has(value.tag))throw new Error('预览元素不安全');const element=document.createElement(value.tag);if(value.text)element.textContent=value.text;for(const [name,entry] of Object.entries(value.attributes??{})){if(!ATTRIBUTES.has(name)||name.startsWith('on'))throw new Error('预览属性不安全');if(['href','src'].includes(name)&&!safeUrl(entry))throw new Error('预览链接不安全');if(entry!==undefined)element.setAttribute(name,String(entry));}if(value.editorId){element.dataset.editorId=value.editorId;element.tabIndex=0;}for(const child of value.children??[])append(element,child,document);parent.append(element); }

export function renderPreview(model,iframeDocument,onSelect) {
  iframeDocument.replaceChildren();const html=iframeDocument.createElement('html');html.lang='en';const head=iframeDocument.createElement('head');const meta=iframeDocument.createElement('meta');meta.name='viewport';meta.content='width=device-width';const link=iframeDocument.createElement('link');link.rel='stylesheet';link.href='/assets/public-global.css';const style=iframeDocument.createElement('style');style.textContent='[data-editor-id]{outline-offset:4px;cursor:pointer}[data-editor-id]:hover,[data-editor-id]:focus{outline:2px solid #b56c20}';head.append(meta,link,style);const body=iframeDocument.createElement('body');body.style.cssText=`--background:${model.theme.background};--surface:${model.theme.surface};--text:${model.theme.text};--accent:${model.theme.accent};--focus:${model.theme.focus}`;const main=iframeDocument.createElement('main');main.id='main-content';for(const value of model.nodes)append(main,value,iframeDocument);body.append(main);html.append(head,body);iframeDocument.append(html);
  main.addEventListener('click',event=>{event.preventDefault();const selected=event.target.closest('[data-editor-id]');if(selected)onSelect?.(selected.dataset.editorId);});
}
